.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 2/26/12
.Dt magicmouse 1
.Os MacOSX
.Sh NAME
.Nm magicmouse
.Sh SYNOPSIS
.Nm
.Op Fl hp
.Op Fl d Ar exportPath
.Op Fl r Ar path
.Op Fl s Ar scaleFactor
.Ar cursorPath
.Sh DESCRIPTION   
A tool to change the cursor of Mac OS X 10.7+ to a mightymouse cursor file. Only applies until logout.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl h
Shows the help.
.It Fl p
Sets the cursor to that of the preferences. (Only used in conjunction with the Magic Mouse Preference Pane.)
.It Fl d Ar path
Dumps the a few common cursors to the path specified.
.It Fl r Ar path
Sets the cursor to original system cursors contained in the Mighty Mouse file specified.
.It Fl s Ar factor
Scales the cursor by the factor specified. (ex. '-s 0.5' shrinks the cursor to half its size.)
.It Fl s
Gets the current scale factor of the cursor.
.It Ar cursorPath
Specifying no options sets the cursor to the specified Mighty Mouse file.
.El
.Sh Author
Created by Alex Zielenski © 2012. alex@alexzielenski.com